name: Validate pull request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "rust-cache"

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Install Rust target (Linux)
        if: runner.os == 'Linux'
        run: rustup target add x86_64-unknown-linux-musl

      - name: Install musl tools (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get install -y musl-tools

      - name: Build
        run: just build

      - name: Test
        run: just test
